### ISSUE TITLE
Menu appears and then disappears

### ISSUE THREAD

**Issue by svroonland** [code-star/codestar-website#23]

**Comment by mozartdiniz** [comment]
@mvdam It looks like that your code from "https://github.com/code-star/codestar-website/commit/b13a0c0aa24018a841a5a6f23947d3208c8bb7d3" solves this issue.

This code:
```css
#fixed-menu .menu {
  display: none;
  margin-top: 0.2em;
  clear: both;
  float: left;
  margin-left: 1.7em;
}
```
